title = "LOWORK CO."
description = "Loworks is a software design and development agency.  We help individuals and businesses of all sizes to design and develop business driven digital solutions."
baseURL = "https://loworks-two.netlify.com/"
languageCode = "en-us"