title = "LOWORK CO."
description = "Loworks is a software design and development agency.  We help individuals and businesses of all sizes to design and develop business driven digital solutions."
baseURL = "https://loworks-two.netlify.com/"
# disable language
disableLanguages = []
DefaultContentLanguage = "en"

[params]
  DisableLanguageSwitchingButton = "true"

################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
dataDir = "data/en"

################################ Chinese Language ########################
[Languages.zh]
languageName = "中文"
languageCode = "zh-zh"
dataDir  = "data/zh"