title = "Loworks - Applications Development for Organisations"
description = "Loworks is a software design and development agency.  We help individuals and businesses of all sizes to design and develop business driven digital solutions."
baseURL = "https://loworks-two.netlify.com/"
DefaultContentLanguage = "en"
disableLanguages = []

[params]
DisableLanguageSwitchingButton = "false"

[Languages]

[Languages.en]
languageName = "English"
languageCode = "en-us"
dataDir = "data/en"
contentDir = "content/en"

[Languages.zh]
languageName = "中文"
languageCode = "zh-zh"
dataDir = "data/zh"
contentDir = "content/zh"