backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: "pages1" # Used in routes, e.g., /admin/collections/post
    label: "Header" # Used in the UI
    create: false # Allow users to create new documents in this collection
    delete: false
    editor:
      preview: true
    files:
    - file: "data/cover.json" # The path to the folder where the documents are stored
      label: "Header"
      name: "Header"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
          - {label: 'Image', name: 'illustration', widget: 'image', required: true, default: "/images/covers/freelancing.svg" }