backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: "Setting" # Used in routes, e.g., /admin/collections/post
    label: "Setting" # Used in the UI
    create: false # Allow users to create new documents in this collection
    delete: false # Disallow users to delete new documents in this collection
    editor:
      preview: true
    files:
    - file: "config.toml" # The path to the folder where the documents are stored
      label: "Site"
      name: "Site"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
          - {label: "Domain Name", name: "baseURL", widget: "string", required: true }
          - {label: "DefaultContentLanguage", name: "DefaultContentLanguage", widget: "hidden", default: "en" }
          - {widget: "hidden", name: DisableLanguageSwitchingButton, label: DisableLanguageSwitchingButton, required: true}
    - file: "data/site.json" # The path to the folder where the documents are stored
      label: "Logo,favicon, Google Analytics"
      name: "sitelfg"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: 'Logo', name: 'logo', widget: 'image', required: true }
          - {label: 'Favicon', name: 'favicon', widget: 'image', required: true }
          - {label: 'Footer logo', name: 'footerlogo', widget: 'image', required: true }
          - {label: "Google Analyticse Code", name: "googleAnalytics", widget: "string" }
    - file: "data/en/nav.json"
      label: "Navigation EN"
      name: "NavigationEN"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Nav Title 1", name: "title2", widget: "string", required: true }
          - {label: "Nav Title 2", name: "title3", widget: "string", required: true }
          - {label: "Nav Title 3", name: "title4", widget: "string", required: true }
    - file: "data/zh/nav.json"
      label: "Navigation ZH"
      name: "NavigationZH"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Nav Title 1", name: "title2", widget: "string", required: true }
          - {label: "Nav Title 2", name: "title3", widget: "string", required: true }
          - {label: "Nav Title 3", name: "title4", widget: "string", required: true }
    - file: "data/en/cover.json" # The path to the folder where the documents are stored
      label: "Header EN"
      name: "HeaderEN"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
          - {label: 'Banner Image', name: 'illustration', widget: 'image', required: true, default: "images/covers/freelancing.svg" }
          - {label: 'Contact button Text', name: 'contactbtn', widget: 'string', required: true }
          - {label: 'Services Link Text', name: 'featuresbtn', widget: 'string', required: true }
    - file: "data/zh/cover.json" # The path to the folder where the documents are stored
      label: "Header ZH"
      name: "HeaderZH"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
          - {label: 'Banner Image', name: 'illustration', widget: 'image', required: true, default: "images/covers/freelancing.svg" }
          - {label: 'Contact button Text', name: 'contactbtn', widget: 'string', required: true }
          - {label: 'Services Link Text', name: 'featuresbtn', widget: 'string', required: true }
    - file: "data/en/services.json"
      label: "Services Title and Description EN"
      name: "ServicesEN"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
    - file: "data/zh/services.json"
      label: "Services Title and Description ZH"
      name: "ServicesZH"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
    - file: "data/en/approach.json"
      label: "Approach Title and Description EN"
      name: "ApproachEN"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
    - file: "data/zh/approach.json"
      label: "Approach Title and Description ZH"
      name: "ApproachZH"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: 'Description', name: 'description', widget: 'string', required: true }
    - file: "data/en/contact.json"
      label: "Contact EN"
      name: "ContactEN"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: "Address text", name: "addresstext", widget: "string", required: true }
          - {label: "Email text", name: "emailtext", widget: "string", required: true }
          - {label: "phone text", name: "phonetext", widget: "string", required: true }
          - {label: "Your Name text", name: "yourname", widget: "string", required: true }
          - {label: "Your Email text", name: "youremail", widget: "string", required: true }
          - {label: "Your Message text", name: "yourmessage", widget: "string", required: true }
          - {label: "Submit button Text", name: "submitbtn", widget: "string", required: true }
          - {label: "Name Placeholder", name: "placeholdername", widget: "string", required: true }
          - {label: "Email Placeholder", name: "placeholderemail", widget: "string", required: true }
          - {label: "Message Placeholder", name: "placeholdermessage", widget: "string", required: true }
    - file: "data/zh/contact.json"
      label: "Contact ZH"
      name: "ContactZH"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: "Address text", name: "addresstext", widget: "string", required: true }
          - {label: "Email text", name: "emailtext", widget: "string", required: true }
          - {label: "phone text", name: "phonetext", widget: "string", required: true }
          - {label: "Your Name text", name: "yourname", widget: "string", required: true }
          - {label: "Your Email text", name: "youremail", widget: "string", required: true }
          - {label: "Your Message text", name: "yourmessage", widget: "string", required: true }
          - {label: "Submit button Text", name: "submitbtn", widget: "string", required: true }
          - {label: "Name Placeholder", name: "placeholdername", widget: "string", required: true }
          - {label: "Email Placeholder", name: "placeholderemail", widget: "string", required: true }
          - {label: "Message Placeholder", name: "placeholdermessage", widget: "string", required: true }
    - file: "data/en/footer.json"
      label: "Footer EN"
      name: "FooterEN"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Copyright Text", name: "footertext", widget: "string", required: true }
    - file: "data/zh/footer.json"
      label: "Footer ZH"
      name: "FooterZH"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Copyright Text", name: "footertext", widget: "string", required: true }
    - file: "data/social.json"
      label: "Social Links for EN and ZH"
      name: "SocialENZh"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Facebook Link", name: "facebook", widget: "string", required: true }
          - {label: "Instagram Link", name: "instagram", widget: "string", required: true }
          - {label: "Twitter Link", name: "twitter", widget: "string", required: true }
          - {label: "Whatsapp Link", name: "whatsapp", widget: "string", required: true }
  - name: "ServicesItemEN" # Used in routes, e.g., /admin/collections/post
    label: "Services Items EN" # Used in the UI
    create: true # Allow users to create new documents in this collection
    delete: true # Disallow users to delete new documents in this collection
    folder: "content/en/services"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: 'Image', name: 'image', widget: 'image', required: true}
      - {label: "Title", name: "title", widget: "string", required: true }
      - {label: 'Description', name: 'description', widget: 'string', required: true }
      - {label: 'Order', name: 'weight', widget: 'number', required: true, valueType: "int" }
  - name: "ServicesItemZH" # Used in routes, e.g., /admin/collections/post
    label: "Services Items ZH" # Used in the UI
    create: true # Allow users to create new documents in this collection
    delete: true # Disallow users to delete new documents in this collection
    folder: "content/zh/services"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: 'Image', name: 'image', widget: 'image', required: true}
      - {label: "Title", name: "title", widget: "string", required: true }
      - {label: 'Description', name: 'description', widget: 'string', required: true }
      - {label: 'Order', name: 'weight', widget: 'number', required: true, valueType: "int" }
  - name: "ApproachItemEN" # Used in routes, e.g., /admin/collections/post
    label: "Approach Items EN" # Used in the UI
    create: true # Allow users to create new documents in this collection
    delete: true # Disallow users to delete new documents in this collection
    folder: "content/en/approach"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: 'Image', name: 'image', widget: 'image', required: true}
      - {label: "Title", name: "title", widget: "string", required: true }
      - {label: 'Description', name: 'description', widget: 'string', required: true }
      - {label: 'Order', name: 'weight', widget: 'number', required: true, valueType: "int" }
  - name: "ApproachItemZH" # Used in routes, e.g., /admin/collections/post
    label: "Approach Items ZH" # Used in the UI
    create: true # Allow users to create new documents in this collection
    delete: true # Disallow users to delete new documents in this collection
    folder: "content/zh/approach"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: 'Image', name: 'image', widget: 'image', required: true}
      - {label: "Title", name: "title", widget: "string", required: true }
      - {label: 'Description', name: 'description', widget: 'string', required: true }
      - {label: 'Order', name: 'weight', widget: 'number', required: true, valueType: "int" }